version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - echo Installing Trivy...
      - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 484907526019.dkr.ecr.us-east-1.amazonaws.com

      - echo Running Trivy FS Scan...
      - trivy fs --exit-code 0 --severity HIGH,CRITICAL --format table -o trivy-fs-report.html .
  build:
    commands:
      - echo Build started on `date`
      - docker build -t ecommerce-app .
      - docker tag ecommerce-app:latest 484907526019.dkr.ecr.us-east-1.amazonaws.com/ecommerce-app:latest
  post_build:
    commands:
      - echo Pushing image...
      - docker push 484907526019.dkr.ecr.us-east-1.amazonaws.com/ecommerce-app:latest
      - echo Writing imagedefinitions.json...
      - echo '[{"name":"app","imageUri":"484907526019.dkr.ecr.us-east-1.amazonaws.com/ecommerce-app:latest"}]' > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
    - trivy-fs-report.html
