version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin <ACCOUNT>.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - docker build -t ecommerce-app .
      - docker tag ecommerce-app:latest <ACCOUNT>.dkr.ecr.us-east-1.amazonaws.com/ecommerce-app:latest
  post_build:
    commands:
      - echo Pushing image...
      - docker push <ACCOUNT>.dkr.ecr.us-east-1.amazonaws.com/ecommerce-app:latest
      - printf '[{\"name\":\"app\",\"imageUri\":\"<ACCOUNT>.dkr.ecr.us-east-1.amazonaws.com/ecommerce-app:latest\"}]' > imagedefinitions.json

artifacts:
  files: imagedefinitions.json
