version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 484907526019.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - docker build -t ecommerce-app .       # <-- FIXED: use dot, not double-dot
      - docker tag ecommerce-app:latest 484907526019.dkr.ecr.us-east-1.amazonaws.com/ecommerce-app:latest
  post_build:
    commands:
      - echo Pushing image...
      - docker push 484907526019.dkr.ecr.us-east-1.amazonaws.com/ecommerce-app:latest
      - echo '[{"name":"app","imageUri":"484907526019.dkr.ecr.us-east-1.amazonaws.com/ecommerce-app:latest"}]' > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
